project:
  type: website
  output-dir: docs

execute: 
  freeze: auto

website:
  title: "Dialectic with Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: litera
    css: styles.css

editor: visual

