project:
  type: website
  output-dir: docs

execute: 
  freeze: auto

website:
  title: "Dialectic with Data"
  navbar:
    right:
      - blog.qmd
      - about.qmd
      - icon: github
        href: https://github.com/sweiner123
      - icon: linkedin
        href: https://www.linkedin.com/in/sam-weiner/
format:
  html:
    theme: litera
    css: styles.css

editor: visual

