---
title: "Tidy Tuesday - World Cup Edition"
author: "Sam Weiner"
date: "2022-12-11"
categories: [tidytuesday, analysis]
---

# TidyTuesday

Tidy Tuesday is an awesome initiative by the R for Data Science Community where data sets are published every week for the R community share any analysis and visualizations that can be conjured from the data!

## World Cup Data

This data set contains data on every World Cup since 1930.

```{r, include=FALSE}
library(tidyverse)
library(tidytuesdayR)
library(tidymodels)
theme_set(theme_light())
```

```{r, message=FALSE, echo=FALSE}

tt <- tt_load("2022-11-29")
tt
```

```{r, include=FALSE}

tt %>% 
  map(glimpse)

```

## Load in the World Cup data

```{r}
matches <- tt$wcmatches
wcups <- tt$worldcups

matches %>% view()

matches %>% 
  count(home_score, away_score, sort = TRUE)
```

```{r}
matches |> 
  filter(outcome != "D") |>
  count(winning_team, sort = TRUE)|>
  filter(n > 5) |> 
  ggplot() +
  geom_col(aes(fct_reorder(winning_team, n, max), n)) + 
  coord_flip()
```

```{r}
matches <- matches %>% 
  mutate(stage = if_else(str_detect(stage, "^Group"), "Group",stage)) %>% 
  mutate(stage = if_else(str_detect(stage, "^ Group"), "Group",stage)) %>% 
  mutate(dayofweek = factor(dayofweek, c("Monday", "Tuesday", "Wednesday",
                                         "Thursday", "Friday", "Saturday", 
                                         "Sunday")))

```

```{r}
matches %>%
  filter(stage != "Group")|>
  ggplot(aes(dayofweek, fill = stage)) + 
  geom_bar()
```

```{r}
wcups %>% view()

wcups %>% 
  count(year, wt = goals_scored, sort = TRUE)

wcups %>% 
  ggplot(aes(year, goals_scored)) +
  geom_line() +
  geom_line(aes(year, games))


```
