---
title: "R resources for Practicum"
author: "Sam Weiner"
editor: visual
toc: true
number-sections: true
highlight-style: pygments
---

# A Mishmash of R resources

Hello again! I'm excited to put another post up on Dialectic with Data where I will be brain dumping some of the awesome R resources I have ran across in my journey learning and loving R! This post is was specifically inspired by my practicum team because I have enjoyed sharing these resources with them over time, but many of them have been lost deep in the depths of our slack channel. So, I am going to be cataloging many of the things that I have shared with them, and I will also be adding new resources as I come upon them for them and you!

## General R tips

### R for Data Science

My biggest and most valuable tip to learning R is read [R for Data Science by Hadley](https://r4ds.had.co.nz/) Wickham and Garret Grolemund.This book has so much knowledge stored inside it. It primarily teaches the [tidyverse](https://www.tidyverse.org/) and its wonderful array of tools for exploratory data analysis and data visualization. It has been a bible for me, and I see myself turning back to it more often than one would think for a self-classified introductory book. The second version is currently under development but available to read [here](https://r4ds.hadley.nz/).

### Rstudio Projects

Rstudio projects are a convenient and efficient way of organizing all of the code, data, and visualizations that make up a data science project. The biggest efficiency boost in my experience is that your working directory automatically updates to the folder where your Rstudio project lives, so all of you code and visualizations are automatically saved in the same place. Additionally, any data that you have in, for example, a csv file can be easily uploaded to your environment without having to mess with the working directory. Other important features that are a bit more advanced revolve around Rstudio projects ability to improve reproducibility and use version control.

-   Resources for learning more about Rstudio Projects
    -   [Intro to Rstudio Projects](https://support.posit.co/hc/en-us/articles/200526207-Using-RStudio-Projects)
    -   [Rstudio and reproducibility](https://rstudio.github.io/renv/articles/renv.html)
    -   [Rstudio and git](https://happygitwithr.com/index.html)

### Shortcuts, Tips, and Tricks

The Rstudio IDE is probably the best IDE (integrated development environment) for using R and conducting data science tasks in general. It has stiff competition from the likes of Visual Studio Code, but there are a few tips and tricks that I am going to show you for Rstudio that might make you think twice before switching to a different IDE.

-   `Alt + -`
    -   Shortcut for inserting the assignment operator `<-`
-   `Ctrl + Shift + M`
    -   Shortcut for inserting the pipe magrittr operator `%>%` commonly used in the tidyverse
    -   Note: As of R 4.1.0, R has a built in pipe operator `|>` which works similarly to the magrittr pipe but has same slight nuances. See [here](https://ivelasq.rbind.io/blog/understanding-the-r-pipe/) and [here](https://stackoverflow.com/questions/67744604/what-does-pipe-greater-than-mean-in-r) for more information on the built in pipe operator.\
-   `Ctrl + Shift + R`
    -   Creates a comment section header in an R source file which is collapseable and also creates an outline to easily navigate your code file.
-   `Ctrl + Shift + Alt + M`
    -   Renames a variable in the entire file. Just highlight the variable to be renamed, use the shortcut, and type the new name. Easy as that!
    -   Using `Ctrl + F` and using replace is another option which is useful when you don't want to rename every instance of a variable in the file.
-   Code Snippets
    -   Code Snippets are ways to insert commonly used code structures (or headers) in an R file. Under the *Tools* toolbar, go to *Edit Code Snippets*. There you will see all the code snippets pre-built in Rstudio and and editor for adding new ones. I use this to add a header structure to new scripts where I can fill in information about the script for my teammates to read when they use it.
-   Multiple Cursors
    -   This was a tip that I was sorely missing from my time using VS Code until I stumbled upon this simple shortcut in Rstudio! Just by holding down the `Alt` button and clicking or draging with the mouse, you'll have more cursors than you know what to do with.

More awesome shortcuts can be found in this [awesome article by Appsilon](https://appsilon.com/rstudio-shortcuts-and-tips/)

### Quarto

Quarto is Rstudio's (now called Posit) new Rmarkdown replacement. The biggest change from Rmarkdown to Quarto is that you can use Quarto in Jupyter Notebooks! Posit (formerly Rstudio) is broadening it's presence in the data science community by engaging with python users in addition to R users. The hope, says Posit, is to create easy tools for cross-language collaboration so that researchers and data scientists can use their languages of choice and still work together. From what I have seen, many data scientists who might have preferred R as a language have been pressured to use python because of its large presence in the data science community. This tool is hopefully going to create a pathway for R users to stay R users without complicating team workflows in a python-dominant environment.

In addition, Quarto has some awesome features such as helping users easily create documents, presentation, or even blogs (like this one!). So far, it has been very intuitive and the documentation has been very helpful. You can find information at [quarto.org](https://quarto.org).

## Packages

Now lets get to packages! I am going to be listing packages that I think are really helpful (and really cool) for working with data and doing modeling in R.

### Tidyverse

-   [ggplot2](https://ggplot2.tidyverse.org/)
    -   This package contains the best tools for taking data and making a stellar visualization out of it. It is extremely versatile and at times very complicated. Later on I will be sharing more about ggplot2 and provide some resources for making ggplot2 super easy to understand.
-   [dplyr](https://dplyr.tidyverse.org/)
    -   This package has the tools you need to manipulate data. Mutate is useful for feature engineering and summarise is great for calculating summaries of your data set. Using the piping syntax makes this package so powerful. My favorite way of using this package is to dig into the data and pipe what I want into a ggplot!
-   [readr](https://readr.tidyverse.org/)
    -   This package makes importing data easy as can be.
-   [purrr](https://purrr.tidyverse.org/)
    -   This package contains the tidyverse's toolkit for functional programming. The [iteration chapter](http://r4ds.had.co.nz/iteration.html) in R for Data Science is a great place to start if you are new to functional programming. Another great resources I used is [purrr tutorial](https://jennybc.github.io/purrr-tutorial/index.html) by Jenny Bryan. Functional programming has been very hard for me, but these two resources have really helped me wrap my brain around the concept, and it has already impacted by projects enormously.
-   [stringr](https://stringr.tidyverse.org/)
    -   stringr is the handiest way of working with strings in R. It has everything under the sun when it comes to manipulating and cleaning character data.
-   [forcats](https://forcats.tidyverse.org/)
    -   Factors are a very common data type in R, but they can be tricky at times. This package has some awesome tools for working with factors that will really come in handy if you use factors a lot.

### Tidymodels

Tidymodels is a standalone universe which has everything you need to do machine learning in R. The tidymodels project is headed by the same person that create CARET years back, Max Kuhn, and the goal of tidymodels is the same as CARETS goal: To create a unified interface for machine learning in R. The package makes use of R's rich ecosystem of machine learning model implementations but standardizes the interface across all those implemetations to make the switch between model implementations seamless. The amount of packages and tools in the tidymodels universe is large and there is too much to say for this blog post. However, I do plan on showing how tidymodels is used in a future blog post, so stay tuned! In the meantime, I am going to point you to some amazing resources if you want to get started now.

-   [Tidy Modeling with R](https://www.tmwr.org/) is a free book written by Max Kuhn and Julia Silge which is the best resource for getting started with tidymodels and it also has some great information on machine learning in general!
-   [tidymodels.org](https://www.tidymodels.org/) has some amazing content which will be the preferred resource for people who want a shorter format introduction to tidymodels.
-   [juilasilge.com](https://juliasilge.com/categories/tidymodels/) is the blog of one of the co-authors of Tidy Modeling with R and she has some great blog posts and youtube videos where she implements the tidymodels packages and gives great explanations of what she is doing.

### Awesome Packages

The Awesome Packages section is going to be a growing list of packages that I find really cool because they have either changed and/or improved the way I use R as a data science student.

#### broom

[broom](https://broom.tidymodels.org/) is a super cool R package. One of the most annoying aspects of using R for data science is trying to extract the output from the model object. Summaries of the model object are easy enough to get using `summary()`, but to extract the components of model like the coefficients, pvalues, or Rsquared value to use for other operations means digging into the model object and trying and failing to use the right index to find it. broom makes that task no more. By using the `tidy()` function on supported model objects, the output is represented as a data frame which makes extracting what you want so much easier. Rsquared and other metric vaules can be found by using `glance()` and `augment()` can add output like predictions from a new datas et back into the data set from whence it came.

## Causal Inference

Causal inference is a topic that I have been learning about a lot lately. As someone who does not have a formal background in statistics or epidemiology, it has been important to me to find resources that teach causal inference in terms that I can understand. Here is a list of resources and R packages that can help you if you are interested in causal inference.

-   [Causal Inference in R](https://www.r-causal.org/) is a ongoing book project by Malcolm Barrett, Lucy D'Agostino McGowan, and Travis Gerke. It contains some amazing information at the moment and it will only get better as the authors work on it.
-   [Causal Inference for The Brave and True](https://matheusfacure.github.io/python-causality-handbook/landing-page.html) by Matheus Facure Alves is a book that has great explanations of causal inference techniques and concepts and everything coding related is written in python for those interested in a python implementation of causal inference!
-   [Causal Inference: What If?](https://cdn1.sph.harvard.edu/wp-content/uploads/sites/1268/2022/11/hernanrobins_WhatIf_13nov22.pdf) by Miguel A. Hernán and James M. Robins is causal inference bible. It is much heavier than the resources above and the focus is purely on the methodology of causal inference. However R code which follows part 2 of the book chapter by chapter can be found [here](https://causalinferencebookr.netlify.app/).
-   [Workshop: Causal Inference in R](https://www.youtube.com/watch?v=n8c-UK19hbA) is a video workshop by Malcolm Barrett and Lucy D'Agostino McGowan. The workshop has been updated since the video but no new video has surfaced that I could find. The new workshop can be found on github [here](https://github.com/malcolmbarrett/causal_inference_r_workshop) with the slides and exercise rmarkdown files. The solutions to the exercises can be found [here](https://github.com/malcolmbarrett/causal_inference_r_workshop_solutions)
-   [MatchIt](https://kosukeimai.github.io/MatchIt/) is a package that creates matches based on observational data. It has awesome vignettes on its website that explains matching for causal inference in detail and has many method options to implement for matching
-   [ggdag](https://ggdag.malco.io/) is a way to plot directed acyclic dags (DAGs) in R using more a ggplot2-like interface as opposed to [daggity](http://www.dagitty.net/primer/).
-   [propensity](https://github.com/malcolmbarrett/propensity) helps calculate propensity scores and weights for a wide variety of research questions.propensity is under very early development.
-   [tipr](https://lucymcgowan.github.io/tipr/) After fitting your model, you can determine the unmeasured confounder needed to tip your analysis.
-   [halfmoon](https://github.com/malcolmbarrett/halfmoon)\[https://github.com/malcolmbarrett/halfmoon\] The goal of halfmoon is to cultivate balance in propensity score models.
